name = "GenSquareDimNums"
uuid = "d02700c8-d93e-456e-a910-022ba761a515"
authors = ["Laine Taffin Altman <alexanderaltman@me.com> and contributors"]
version = "0.0.0-DEV"

[weakdeps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extensions]
GenSquareDimNumsStatisticsExt = "Statistics"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
