name = "GenSquareDimNums"
uuid = "d02700c8-d93e-456e-a910-022ba761a515"
authors = ["Laine Taffin Altman <alexanderaltman@me.com> and contributors"]
version = "0.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
